//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use serde::Deserialize;
use serde::Serialize;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq,Serialize, Deserialize)]
#[sea_orm(table_name = "character_propety")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub character_id: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((13, 4)))", nullable)]
    pub health_point: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((13, 4)))", nullable)]
    pub mana_point: Option<Decimal>,
    pub bazi_year_tiangan: Option<i32>,
    pub bazi_year_dizhi: Option<i32>,
    pub bazi_month_tiangan: Option<i32>,
    pub bazi_month_dizhi: Option<i32>,
    pub bazi_day_tiangan: Option<i32>,
    pub bazi_day_dizhi: Option<i32>,
    pub bazi_hour_tiangan: Option<i32>,
    pub bazi_hour_dizhi: Option<i32>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
